import {
  budgets,
  categoryMonthlyAggregate,
  charLinetMultipleData,
  chartLineLinearData,
  pieChart,
} from "./types";

export const transactionsLedger: chartLineLinearData[] = [
  {
    month: "September",
    transactions: [
      { day: "30", amount: 59.5 },
      { day: "30", amount: 9782.33 },
      { day: "30", amount: 135.0 },
    ],
  },
  {
    month: "October",
    transactions: [
      { day: "01", amount: -53.0 },
      { day: "01", amount: -74.0 },
      { day: "01", amount: -112.0 },
      { day: "01", amount: -400.0 },
      { day: "01", amount: -410.41 },
      { day: "01", amount: -2.0 },
      { day: "02", amount: -250.0 },
      { day: "02", amount: 1557.86 },
      { day: "04", amount: -515.87 },
      { day: "04", amount: -1.99 },
      { day: "07", amount: -1569.0 },
      { day: "07", amount: -379.0 },
      { day: "07", amount: -467.91 },
      { day: "07", amount: -529.0 },
      { day: "07", amount: -7000.0 },
      { day: "10", amount: -159.3 },
      { day: "10", amount: -115.71 },
      { day: "11", amount: -9.72 },
      { day: "11", amount: -9.72 },
      { day: "11", amount: -73.5 },
      { day: "11", amount: -0.55 },
      { day: "11", amount: -1.21 },
    ],
  },
];

export const incomeExpenseLedger: charLinetMultipleData[] = [
  {
    month: "September",
    transactions: [
      { day: "30", income: 0, expense: 59.5 },
      { day: "30", income: 9782.33, expense: 0 },
      { day: "30", income: 0, expense: 135.0 },
      { day: "30", income: 0, expense: 0.0 },
    ],
  },
  {
    month: "October",
    transactions: [
      { day: "01", income: 0, expense: 53.0 },
      { day: "01", income: 0, expense: 74.0 },
      { day: "01", income: 0, expense: 112.0 },
      { day: "01", income: 0, expense: 400.0 },
      { day: "01", income: 0, expense: 410.41 },
      { day: "01", income: 0, expense: 2.0 },
      { day: "02", income: 0, expense: 250.0 },
      { day: "02", income: 0, expense: 1557.86 },
      { day: "04", income: 0, expense: 515.87 },
      { day: "04", income: 0, expense: 1.99 },
      { day: "07", income: 1569.0, expense: 0 },
      { day: "07", income: 0, expense: 379.0 },
      { day: "07", income: 0, expense: 467.91 },
      { day: "07", income: 0, expense: 529.0 },
      { day: "07", income: 0, expense: 7000.0 },
      { day: "07", income: 0, expense: 0.0 },
      { day: "10", income: 0, expense: 159.3 },
      { day: "10", income: 0, expense: 115.71 },
      { day: "11", income: 9.72, expense: 0 },
      { day: "11", income: 9.72, expense: 0 },
      { day: "11", income: 0, expense: 73.5 },
      { day: "11", income: 0, expense: 0.55 },
      { day: "11", income: 0, expense: 1.21 },
    ],
  },
];

export const monthlyCategoryAggregate: categoryMonthlyAggregate[] = [
  { month: "January", category: "Groceries", totalSpend: 520.35 },
  { month: "January", category: "Transport", totalSpend: 240.5 },
  { month: "January", category: "EatingOutAndTreats", totalSpend: 310.2 },
  { month: "January", category: "GeneralRetail", totalSpend: 180.0 },
  { month: "January", category: "Fuel", totalSpend: 350.75 },
  { month: "January", category: "ProfessionalServices", totalSpend: 120.0 },
  { month: "January", category: "PharmaciesAndWellbeing", totalSpend: 95.6 },
  { month: "January", category: "MusicGamingApps", totalSpend: 29.99 },

  { month: "February", category: "Groceries", totalSpend: 480.1 },
  { month: "February", category: "Transport", totalSpend: 262.9 },
  { month: "February", category: "EatingOutAndTreats", totalSpend: 282.0 },
  { month: "February", category: "GeneralRetail", totalSpend: 210.0 },
  { month: "February", category: "Fuel", totalSpend: 330.4 },
  { month: "February", category: "ProfessionalServices", totalSpend: 90.0 },
  { month: "February", category: "HomewareAndAppliances", totalSpend: 150.0 },
  { month: "February", category: "DonationsAndGiving", totalSpend: 50.0 },

  { month: "March", category: "Groceries", totalSpend: 560.0 },
  { month: "March", category: "Transport", totalSpend: 275.0 },
  { month: "March", category: "EatingOutAndTreats", totalSpend: 340.0 },
  { month: "March", category: "GeneralRetail", totalSpend: 220.0 },
  { month: "March", category: "Fuel", totalSpend: 372.5 },
  { month: "March", category: "TravelAndHolidays", totalSpend: 820.0 },
  { month: "March", category: "PharmaciesAndWellbeing", totalSpend: 60.0 },
  { month: "March", category: "CarUseAndServices", totalSpend: 200.0 },

  { month: "April", category: "Groceries", totalSpend: 510.0 },
  { month: "April", category: "Transport", totalSpend: 232.0 },
  { month: "April", category: "EatingOutAndTreats", totalSpend: 295.0 },
  { month: "April", category: "GeneralRetail", totalSpend: 170.0 },
  { month: "April", category: "Fuel", totalSpend: 360.0 },
  { month: "April", category: "ProfessionalServices", totalSpend: 405.0 },
  { month: "April", category: "HomewareAndAppliances", totalSpend: 210.0 },
  { month: "April", category: "OutdoorAndAdventure", totalSpend: 180.0 },

  { month: "May", category: "Groceries", totalSpend: 542.0 },
  { month: "May", category: "Transport", totalSpend: 258.0 },
  { month: "May", category: "EatingOutAndTreats", totalSpend: 318.0 },
  { month: "May", category: "GeneralRetail", totalSpend: 212.0 },
  { month: "May", category: "Fuel", totalSpend: 381.0 },
  { month: "May", category: "TravelAndHolidays", totalSpend: 1205.0 },
  { month: "May", category: "Hobbies", totalSpend: 140.0 },
  { month: "May", category: "GiftsAndFlowers", totalSpend: 92.0 },

  { month: "June", category: "Groceries", totalSpend: 505.0 },
  { month: "June", category: "Transport", totalSpend: 246.0 },
  { month: "June", category: "EatingOutAndTreats", totalSpend: 312.0 },
  { month: "June", category: "GeneralRetail", totalSpend: 195.0 },
  { month: "June", category: "Fuel", totalSpend: 356.0 },
  { month: "June", category: "ProfessionalServices", totalSpend: 300.0 },
  { month: "June", category: "MusicGamingApps", totalSpend: 49.99 },
  { month: "June", category: "PharmaciesAndWellbeing", totalSpend: 80.0 },

  { month: "July", category: "Groceries", totalSpend: 592.0 },
  { month: "July", category: "Transport", totalSpend: 302.0 },
  { month: "July", category: "EatingOutAndTreats", totalSpend: 362.0 },
  { month: "July", category: "GeneralRetail", totalSpend: 231.0 },
  { month: "July", category: "Fuel", totalSpend: 401.0 },
  { month: "July", category: "HomewareAndAppliances", totalSpend: 262.0 },
  { month: "July", category: "OutdoorAndAdventure", totalSpend: 225.0 },
  { month: "July", category: "DonationsAndGiving", totalSpend: 70.0 },

  { month: "August", category: "Groceries", totalSpend: 615.0 },
  { month: "August", category: "Transport", totalSpend: 311.0 },
  { month: "August", category: "EatingOutAndTreats", totalSpend: 382.0 },
  { month: "August", category: "GeneralRetail", totalSpend: 245.0 },
  { month: "August", category: "Fuel", totalSpend: 412.0 },
  { month: "August", category: "TravelAndHolidays", totalSpend: 910.0 },
  { month: "August", category: "CarUseAndServices", totalSpend: 352.0 },
  { month: "August", category: "Hobbies", totalSpend: 125.0 },

  { month: "September", category: "Groceries", totalSpend: 468.0 },
  { month: "September", category: "EatingOutAndTreats", totalSpend: 518.0 },
  { month: "September", category: "Transport", totalSpend: 400.0 },
  { month: "September", category: "GeneralRetail", totalSpend: 180.0 },
  { month: "September", category: "HomewareAndAppliances", totalSpend: 115.0 },
  { month: "September", category: "DonationsAndGiving", totalSpend: 250.0 },
  { month: "September", category: "ProfessionalServices", totalSpend: 150.0 },
  { month: "September", category: "Fuel", totalSpend: 365.0 },

  { month: "October", category: "Groceries", totalSpend: 512.0 },
  { month: "October", category: "EatingOutAndTreats", totalSpend: 430.0 },
  { month: "October", category: "Transport", totalSpend: 382.0 },
  { month: "October", category: "GeneralRetail", totalSpend: 240.0 },
  { month: "October", category: "ProfessionalServices", totalSpend: 410.0 },
  { month: "October", category: "Fuel", totalSpend: 392.0 },
  { month: "October", category: "MusicGamingApps", totalSpend: 39.99 },
  { month: "October", category: "PharmaciesAndWellbeing", totalSpend: 70.0 },

  { month: "November", category: "Groceries", totalSpend: 499.0 },
  { month: "November", category: "Transport", totalSpend: 295.0 },
  { month: "November", category: "EatingOutAndTreats", totalSpend: 305.0 },
  { month: "November", category: "GeneralRetail", totalSpend: 260.0 },
  { month: "November", category: "Fuel", totalSpend: 370.0 },
  { month: "November", category: "HomewareAndAppliances", totalSpend: 280.0 },
  { month: "November", category: "GiftsAndFlowers", totalSpend: 130.0 },
  { month: "November", category: "PharmaciesAndWellbeing", totalSpend: 85.0 },

  { month: "December", category: "Groceries", totalSpend: 640.0 },
  { month: "December", category: "Transport", totalSpend: 330.0 },
  { month: "December", category: "EatingOutAndTreats", totalSpend: 520.0 },
  { month: "December", category: "GeneralRetail", totalSpend: 420.0 },
  { month: "December", category: "Fuel", totalSpend: 405.0 },
  { month: "December", category: "TravelAndHolidays", totalSpend: 1500.0 },
  { month: "December", category: "GiftsAndFlowers", totalSpend: 350.0 },
  { month: "December", category: "OutdoorAndAdventure", totalSpend: 260.0 },
];

export const pieChartData: pieChart[] = [
  {
    category: "GeneralRetail",
    totalSpend: 180,
    fill: "var(--color-GeneralRetail)",
  },
  {
    category: "Transport",
    totalSpend: 400,
    fill: "var(--color-Transport)",
  },
  {
    category: "EatingOutAndTreats",
    totalSpend: 518,
    fill: "var(--color-EatingOutAndTreats)",
  },
  {
    category: "Fuel",
    totalSpend: 0,
    fill: "var(--color-Fuel)",
  },
  {
    category: "Groceries",
    totalSpend: 468,
    fill: "var(--color-Groceries)",
  },
  {
    category: "ProfessionalServices",
    totalSpend: 410,
    fill: "var(--color-ProfessionalServices)",
  },
  {
    category: "CarUseAndServices",
    totalSpend: 0,
    fill: "var(--color-CarUseAndServices)",
  },
  {
    category: "DonationsAndGiving",
    totalSpend: 250,
    fill: "var(--color-DonationsAndGiving)",
  },
  {
    category: "GiftsAndFlowers",
    totalSpend: 0,
    fill: "var(--color-GiftsAndFlowers)",
  },
  {
    category: "Hobbies",
    totalSpend: 0,
    fill: "var(--color-Hobbies)",
  },
  {
    category: "HomewareAndAppliances",
    totalSpend: 115,
    fill: "var(--color-HomewareAndAppliances)",
  },
  {
    category: "MusicGamingApps",
    totalSpend: 0,
    fill: "var(--color-MusicGamingApps)",
  },
  {
    category: "OutdoorAndAdventure",
    totalSpend: 0,
    fill: "var(--color-OutdoorAndAdventure)",
  },
  {
    category: "PharmaciesAndWellbeing",
    totalSpend: 0,
    fill: "var(--color-PharmaciesAndWellbeing)",
  },
  {
    category: "TravelAndHolidays",
    totalSpend: 0,
    fill: "var(--color-TravelAndHolidays)",
  },
  {
    category: "Other",
    totalSpend: 80,
    fill: "var(--color-Other)",
  },
];

export const userBudgets: budgets[] = [
  {
    category: "GeneralRetail",
    budgetAmount: 1200,
    spentAmount: 850,
    remainingAmount: 350,
  },
  {
    category: "Transport",
    budgetAmount: 600,
    spentAmount: 420,
    remainingAmount: 180,
  },
  {
    category: "EatingOutAndTreats",
    budgetAmount: 900,
    spentAmount: 650,
    remainingAmount: 250,
  },
  {
    category: "Fuel",
    budgetAmount: 1000,
    spentAmount: 780,
    remainingAmount: 220,
  },
  {
    category: "Groceries",
    budgetAmount: 1500,
    spentAmount: 1250,
    remainingAmount: 250,
  },
  {
    category: "ProfessionalServices",
    budgetAmount: 2000,
    spentAmount: 1200,
    remainingAmount: 800,
  },
  {
    category: "CarUseAndServices",
    budgetAmount: 800,
    spentAmount: 650,
    remainingAmount: 150,
  },
  {
    category: "DonationsAndGiving",
    budgetAmount: 400,
    spentAmount: 200,
    remainingAmount: 200,
  },
  {
    category: "GiftsAndFlowers",
    budgetAmount: 500,
    spentAmount: 350,
    remainingAmount: 150,
  },
  {
    category: "Hobbies",
    budgetAmount: 700,
    spentAmount: 400,
    remainingAmount: 300,
  },
  {
    category: "HomewareAndAppliances",
    budgetAmount: 2500,
    spentAmount: 1800,
    remainingAmount: 700,
  },
  {
    category: "MusicGamingApps",
    budgetAmount: 300,
    spentAmount: 200,
    remainingAmount: 100,
  },
  {
    category: "OutdoorAndAdventure",
    budgetAmount: 1000,
    spentAmount: 450,
    remainingAmount: 550,
  },
  {
    category: "PharmaciesAndWellbeing",
    budgetAmount: 600,
    spentAmount: 9000,
    remainingAmount: 280,
  },
  {
    category: "TravelAndHolidays",
    budgetAmount: 4000,
    spentAmount: 2750,
    remainingAmount: 1250,
  },
];
