<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-statement_worker-7a66bb67-d778-4414-98a8-522729514ec4</UserSecretsId>
    <RootNamespace>StatementWorker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.4.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BudgetlyAI.Contracts\BudgetlyAI.Contracts.csproj" />
  </ItemGroup>
</Project>
